# Generated by Django 3.2.5 on 2021-08-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apost',
            old_name='likes',
            new_name='like_count',
        ),
    ]
