# Generated by Django 3.2.5 on 2021-08-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='sent',
        ),
    ]
