# Generated by Django 3.2.5 on 2021-08-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_likes_apost_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apost',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
