# Generated by Django 3.2.5 on 2021-07-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_a_post_apost'),
    ]

    operations = [
        migrations.AddField(
            model_name='apost',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apost',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
