# Generated by Django 3.2.5 on 2021-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_apost_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='session',
            name='reason',
            field=models.CharField(default='null', max_length=256),
            preserve_default=False,
        ),
    ]
