# Generated by Django 3.2.5 on 2021-08-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210803_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='business_type',
        ),
    ]
