# Generated by Django 3.2.5 on 2021-07-28 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20210728_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='apost',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
