# Generated by Django 3.2.5 on 2021-07-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_apost_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
